services:
  - type: web
    name: music-guessing-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: NODE_ENV
        value: production
      - key: HAS_DISK_STORAGE
        value: "false"
      - key: PORT
        value: 10000
    cors:
      allowOrigins:
        - "https://music-guessing-frontend.onrender.com"
        - "https://raw.githubusercontent.com"
        - "https://github.com"
        - "https://linhangdev.software"
      allowMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowHeaders:
        - "Content-Type"
        - "Authorization"
    disk:
      name: music-data
      mountPath: /opt/render/project/src/music
      sizeGB: 1
